# Generated by Django 2.2.2 on 2019-06-12 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('img_src', models.URLField(blank=True, null=True)),
                ('philanthropy_req', models.IntegerField(default='0')),
                ('professional_req', models.IntegerField(default='0')),
                ('tech_req', models.IntegerField(default='0')),
                ('financial_req', models.BooleanField(default=False)),
                ('college_year', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
